FROM rabbitmq:3.12-management
ENV RABBITMQ_USER guest
ENV RABBITMQ_PASSWORD guest
ENV RABBITMQ_PID_FILE /var/lib/rabbitmq/mnesia/rabbitmq
ENV MQTT_DEFAULT_TOPIC_NAME node

ADD init.sh /init.sh
RUN chmod +x /init.sh

EXPOSE 15672
EXPOSE 5672
EXPOSE 1883

CMD ["/init.sh"]